name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas <2
  - s3fs=2024.6
  - bqplot=0.12
  - numpy=1.23
  - nibabel=5.2
  - nilearn=0.10
  - cloudpathlib=0.18
  - pathlib
  - matplotlib=3.9
  - ipywidgets=8.1
