name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas <2
  - s3fs
  - bqplot=0.12
  - numpy <2
  - nibabel
  - nilearn
  - cloudpathlib
  - pathlib
  - matplotlib=3.9
  - ipywidgets=8.1
