name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas <2
  - s3fs
  - bqplot
  - numpy <2
  - nibabel
  - nilearn
  - cloudpathlib
  - pathlib
  - matplotlib
  - ipywidgets >=7.6.0, <8
