name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python=0.15.2
  - pandas <2
  - s3fs=2024.6.1
  - bqplot=0.12.43
  - numpy=1.23.5
  - nibabel=5.2.1
  - nilearn=0.10.4
  - cloudpathlib=0.18.1
  - pathlib
  - matplotlib=3.9.1
  - ipywidgets=8.1.3
